# See https://medium.com/@eng.fadishaar/configuring-nginx-proxy-for-minio-server-using-docker-compose-39921092e050
version: '3.9'

services:
  nginx:
    image: nginx:latest
    hostname: nginx
    ports:
      - "80:80"
      - "443:443"
      - "9001:9001"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/minio.example.com/fullchain.pem:/etc/letsencrypt/live/minio.example.com/fullchain.pem:ro
      - /etc/letsencrypt/live/minio.example.com/privkey.pem:/etc/letsencrypt/live/minio.example.com/privkey.pem:ro
      - /etc/letsencrypt/dhparam.pem:/etc/letsencrypt/dhparam.pem:ro
    networks:
      - minio-network
    depends_on:
      - minio1
  
  minio1:
    image: quay.io/minio/minio:RELEASE.2024-08-03T04-33-23Z
    command: server --address ":9000" --console-address ":9001" /data
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_DOMAIN: minio.example.com
      MINIO_SERVER_URL: https://minio.example.com:9000
      MINIO_BROWSER_REDIRECT_URL: https://minio.example.com:9001
    volumes:
      - ./minio_storage:/data
    networks:
      - minio-network

networks:
  minio-network: