version: '3'

services:
  app1:
    image: nginx:alpine
    container_name: app1
  
  app2:
    image: nginx:alpine
    container_name: app2
  
  nginx:
    image: nginx:latest
    container_name: load_balancer
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Mount custom NGINX config
    depends_on:
      - app1
      - app2
