version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html       # Mount the HTML folder to /var/www/html in the container
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Use the custom NGINX config
